"""
Wingman weekly report generator — produces the numbers, tables and PNG charts
that feed the hackathon write-up. Analysis pipeline only, not the write-up.

Run from the repo root:
    python -m wingman.logging.report

Reads every logs/*.jsonl (globbed, so new days are picked up automatically),
tolerates the three record types (cycle / account_snapshot / scheduler skip)
plus known quirks: Monday's records predate gate_hits and the regime gate
(regime_gate is a plain string there), and Tuesday's file contains one stray
pre-wiring stub record with the same string schema — flagged, not fatal.

FRAMING: every P&L figure in this output is UNREALIZED mark-to-market. No
position has ever been closed by the system and all contracts expire
2026-09-18, after the hackathon ends. Nothing here is realized profit.

OUTPUT FILES (all under reports/, regenerated by every run):
  fit_quality.png       sigma1/sigma2/RMSE per cycle, degenerate-fit
                        rejections marked with an x — shows Monday's isolated
                        bad fits vs Tuesday's sustained degeneracy run.
  moneyness.png         moneyness of every proposed trade over time — the
                        upside-wing model artifact appears as a horizontal
                        band around +1.4-2%.
  equity_unrealized.png account equity and total unrealized P&L across the
                        whole week in one continuous plot.
  gate_comparison.png   trades submitted vs cycles rejected per gate type,
                        one bar group per day — the incident (Monday's
                        unbounded duplication) vs the fix (Tuesday's capped
                        exposure), visually.
  smile_evolution_3d.png strike-moneyness x cycle-time x implied-vol mesh —
                        NOT a true volatility surface (Wingman only ever
                        queries one fixed expiry, 2026-09-18 — there is no
                        expiry axis in this data). Degenerate-fit cycles are
                        excluded (their sigma2 values aren't meaningful IVs).

All four 2D x-axes show ONLY market hours (13:30-20:00 UTC) actually present
in the data, with the line broken (not connected) at day boundaries — no dead
space for the closed overnight period. The 3D chart's cycle-time axis uses the
same market-hours compression, applied per day so surfaces never bridge across
a day boundary.
"""

import json
import math
from datetime import datetime
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.cm import ScalarMappable
from matplotlib.colors import Normalize
from mpl_toolkits.mplot3d import Axes3D  # noqa: F401 — registers the 3d projection

PACKAGE_ROOT = Path(__file__).resolve().parents[1]
LOG_DIR = PACKAGE_ROOT / "logs"
SNAP_DIR = PACKAGE_ROOT / "snapshots"
REPORT_DIR = PACKAGE_ROOT / "reports"

# One shared style so all charts read as one report, not separate scripts.
# Colorblind-considered categorical set (blue/amber/teal/purple, red reserved
# for failure states) — chosen for hue+lightness separation; the project's
# validator script requires Node >=ES6 and this machine's Node (0.12) can't
# run it, so this is a manual choice, not an automated pass.
C_BLUE, C_AMBER, C_TEAL, C_PURPLE, C_RED, C_GRAY = (
    "#1d4ed8", "#b45309", "#0f766e", "#6d28d9", "#dc2626", "#6b7280"
)
plt.rcParams.update({
    "font.family": "sans-serif",
    "font.size": 11,
    "axes.titlesize": 13,
    "axes.titleweight": "bold",
    "axes.labelsize": 10.5,
    "axes.edgecolor": C_GRAY,
    "axes.labelcolor": "#1f2937",
    "text.color": "#1f2937",
    "xtick.color": "#374151",
    "ytick.color": "#374151",
    "legend.fontsize": 9.5,
    "figure.facecolor": "white",
    "axes.facecolor": "white",
    "savefig.facecolor": "white",
})


def _ts(r):
    return datetime.fromisoformat(r["timestamp"])


def load_days():
    """{date_str: {"cycles": [...], "accounts": [...], "sched": [...],
                   "flagged": [...]}} in chronological order."""
    days = {}
    for path in sorted(LOG_DIR.glob("*.jsonl")):
        day = days.setdefault(path.stem, {"cycles": [], "accounts": [], "sched": [], "flagged": []})
        for lineno, line in enumerate(path.open(encoding="utf-8"), 1):
            line = line.strip()
            if not line:
                continue
            try:
                r = json.loads(line)
            except json.JSONDecodeError:
                day["flagged"].append((lineno, "unparseable line"))
                continue
            if r.get("record_type") == "account_snapshot":
                day["accounts"].append(r)
            elif "scheduler" in r:
                day["sched"].append(r)
            elif "timestamp" in r:
                # Known quirk: pre-wiring records carry regime_gate as a plain
                # string. That is every Monday cycle (the gate didn't exist
                # yet) and one stray Tuesday stub; flag the mixed-schema case.
                if isinstance(r.get("regime_gate"), str):
                    r["_pre_gate"] = True
                day["cycles"].append(r)
            else:
                day["flagged"].append((lineno, f"unknown record shape: {list(r)[:4]}"))
    # flag Tuesday-style stubs: a string-schema record in a file where dict
    # records also exist
    for d, day in days.items():
        has_dict = any(isinstance(c.get("regime_gate"), dict) for c in day["cycles"])
        if has_dict:
            for c in day["cycles"]:
                if c.get("_pre_gate"):
                    day["flagged"].append((_ts(c).strftime("%H:%M:%S"),
                                           "pre-wiring stub record (string regime_gate) — excluded from regime stats"))
    return days


def market_hours_axis(day_groups, n_ticks=9):
    """
    Build a compact x-axis with NO dead space for closed-market hours: each
    record gets a sequential integer position (0, 1, 2, ...) in chronological
    order, so overnight/weekend gaps simply don't exist on the axis, matching
    what the scheduler actually produced (it only ever ticks during market
    hours — there is no closed-market data to show a gap for in the first
    place, this just stops matplotlib re-introducing one via a raw datetime
    axis).

    day_groups: list of (day_label, list_of_records) sorted chronologically,
    each record's real timestamp under r["timestamp"].

    Returns:
      id_to_x:    {id(record): x} — look up any record's position, including
                  subsets (e.g. only the degenerate-fit ones) plotted with
                  scatter over a line built from the full set.
      day_segments: [(day_label, [x...], [record...]), ...] — plot ONE line
                  per day using these x/records so the line breaks cleanly at
                  day boundaries instead of connecting across the closed
                  overnight period.
      tick_pos, tick_lab: evenly spaced tick positions and "dd Mon\\nHH:MM"
                  labels sampled from real timestamps, so the compressed axis
                  still reads as wall-clock time.
    """
    id_to_x, day_segments, x = {}, [], 0
    for day_label, recs in day_groups:
        xs = []
        for r in recs:
            id_to_x[id(r)] = x
            xs.append(x)
            x += 1
        if recs:
            day_segments.append((day_label, xs, recs))
    all_recs = [r for _, _, recs in day_segments for r in recs]
    n = len(all_recs)
    if n == 0:
        return id_to_x, day_segments, [], []
    k = min(n_ticks, n)
    idx = sorted({round(i * (n - 1) / max(k - 1, 1)) for i in range(k)})
    tick_pos = [idx_i for idx_i in idx]
    tick_lab = [_ts(all_recs[i]).strftime("%d %b\n%H:%M") for i in idx]
    return id_to_x, day_segments, tick_pos, tick_lab


def _draw_day_boundaries(ax, day_segments):
    """Faint vertical separators between trading days (visual aid only —
    the actual break in each line already happens because each day is a
    separate plot() call, not a connected span)."""
    for day_label, xs, _ in day_segments[1:]:
        ax.axvline(xs[0] - 0.5, color=C_GRAY, lw=0.8, ls=":", alpha=0.5, zorder=1)


def unreal_total(acct_record):
    return sum(p["unrealized_pl"] for p in acct_record.get("positions") or []
               if p.get("unrealized_pl") is not None)


def fit_rmse(cycle):
    """Price-space RMSE from scipy cost: cost = 0.5*sum(res^2) -> sqrt(2c/n)."""
    fit = cycle.get("fit_result")
    n = (cycle.get("snapshot") or {}).get("strikes_used_in_fit")
    if not fit or not n:
        return None
    return math.sqrt(2 * fit["cost"] / n)


def daily_summary(days):
    print("\n== 1. DAILY SUMMARY " + "=" * 58)
    cols = ("date", "cycles", "proposed", "submitted", "spread", "notional",
            "agg-notl", "position", "dir-cflt", "degen", "no-cand",
            "rg full", "rg half", "rg stop",
            "start eq", "end eq", "max unrl", "min unrl")
    rows = []
    for d, day in days.items():
        cycles = day["cycles"]
        proposed = [c for c in cycles if c.get("decision")]
        submitted = [c for c in cycles if c.get("dry_run") is False
                     and (c.get("order_result") or {}).get("response") is not None]
        gh = lambda k: sum((c.get("gate_hits") or {}).get(k, 0) for c in cycles)
        degen = sum(1 for c in cycles if (c.get("fit_result") or {}).get("degenerate_fit"))
        no_cand = sum(1 for c in cycles
                      if c.get("decision") is None and c.get("fit_result")
                      and not c["fit_result"].get("degenerate_fit")
                      and not any((c.get("gate_hits") or {}).values()))
        verdicts = [c["regime_gate"].get("decision") for c in cycles
                    if isinstance(c.get("regime_gate"), dict)]
        accs = day["accounts"]
        unr = [unreal_total(a) for a in accs] or [None]
        eq = [a["account"]["equity"] for a in accs if a.get("account")] or [None]
        fmt = lambda v: f"{v:,.2f}" if isinstance(v, float) else ("-" if v is None else v)
        rows.append((d, len(cycles), len(proposed), len(submitted),
                     gh("spread_gate_hits"), gh("notional_gate_hits"),
                     gh("aggregate_notional_hits"), gh("position_gate_hits"),
                     gh("direction_conflict_hits"), degen, no_cand,
                     verdicts.count("full"), verdicts.count("half"),
                     verdicts.count("stand_down"),
                     fmt(eq[0]), fmt(eq[-1]),
                     fmt(max(unr) if unr[0] is not None else None),
                     fmt(min(unr) if unr[0] is not None else None)))
    widths = [max(len(str(x)) for x in [c] + [r[i] for r in rows]) for i, c in enumerate(cols)]
    print("  " + "  ".join(str(c).rjust(w) for c, w in zip(cols, widths)))
    for r in rows:
        print("  " + "  ".join(str(x).rjust(w) for x, w in zip(r, widths)))
    print("  NOTE: gate-hit counts exist only from 2026-09-01 (gate_hits added then);")
    print("  earlier days show 0 because rejections were printed, not logged.")
    print("  'max/min unrl' are UNREALIZED mark-to-market totals across open positions.")


def _style_axes(*axes):
    for ax in axes:
        ax.spines[["top", "right"]].set_visible(False)
        ax.grid(axis="y", alpha=0.25)


def chart_fit_quality(days):
    day_groups = [(d, [c for c in day["cycles"] if c.get("fit_result")])
                  for d, day in days.items()]
    id_to_x, day_segments, tick_pos, tick_lab = market_hours_axis(day_groups)

    fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(11, 6.5), sharex=True,
                                   gridspec_kw={"height_ratios": [2, 1]})
    for i, (day_label, xs, recs) in enumerate(day_segments):
        lab1 = "sigma2 (stress component)" if i == 0 else None
        lab2 = "sigma1 (calm component)" if i == 0 else None
        lab3 = "fit RMSE (price space)" if i == 0 else None
        ax1.plot(xs, [c["fit_result"]["sigma2"] for c in recs], color=C_AMBER, lw=2, label=lab1)
        ax1.plot(xs, [c["fit_result"]["sigma1"] for c in recs], color=C_BLUE, lw=2, label=lab2)
        ax2.plot(xs, [fit_rmse(c) for c in recs], color=C_TEAL, lw=2, label=lab3)

    degen = [c for _, _, recs in day_segments for c in recs if c["fit_result"].get("degenerate_fit")]
    if degen:
        ax1.scatter([id_to_x[id(c)] for c in degen], [c["fit_result"]["sigma2"] for c in degen],
                    marker="x", s=80, linewidths=2.2, color=C_RED, zorder=5,
                    label=f"rejected by degenerate-fit guard (n={len(degen)})")

    ax1.axhspan(0.05, 1.0, color=C_TEAL, alpha=0.10, zorder=0)
    ax1.annotate("plausible SPY vol band  [0.05, 1.0]\n(fits outside this are rejected, not traded)",
                xy=(0.01, 0.5), xycoords="axes fraction", fontsize=9.5,
                color="#0d5c54", fontweight="bold", va="center",
                bbox=dict(boxstyle="round,pad=0.3", fc="white", ec="none", alpha=0.75))
    ax1.set_ylabel("fitted vol")
    ax1.legend(loc="upper left", frameon=False)
    ax2.set_ylabel("RMSE ($)")
    ax2.legend(loc="upper left", frameon=False)
    _style_axes(ax1, ax2)
    _draw_day_boundaries(ax1, day_segments)
    _draw_day_boundaries(ax2, day_segments)
    ax2.set_xticks(tick_pos)
    ax2.set_xticklabels(tick_lab)
    ax2.set_xlim(-0.5, max(tick_pos) + 0.5 if tick_pos else 1)
    fig.suptitle("Mixture fit quality per cycle — market hours only, degenerate fits marked")
    fig.tight_layout()
    out = REPORT_DIR / "fit_quality.png"
    fig.savefig(out, dpi=150)
    plt.close(fig)
    return out


def chart_moneyness(days):
    day_groups = [(d, [c for c in day["cycles"]
                       if c.get("decision") and (c.get("snapshot") or {}).get("spot")])
                  for d, day in days.items()]
    id_to_x, day_segments, tick_pos, tick_lab = market_hours_axis(day_groups)
    all_recs = [c for _, _, recs in day_segments for c in recs]

    fig, ax = plt.subplots(figsize=(11, 4.6))
    ax.axhspan(1.3, 2.1, color=C_AMBER, alpha=0.14, zorder=0)
    ax.annotate("documented model artifact: proposals cluster ~1.4-2.1%\n"
                "above spot regardless of the underlying signal",
                xy=(0.32, 0.86), xycoords="axes fraction", fontsize=9.5,
                color="#7a3d05", fontweight="bold", ha="left", va="top",
                bbox=dict(boxstyle="round,pad=0.3", fc="white", ec="none", alpha=0.75))
    xs = [id_to_x[id(c)] for c in all_recs]
    mny = [((c["decision"]["strike"] / c["snapshot"]["spot"]) - 1) * 100 for c in all_recs]
    ax.scatter(xs, mny, s=60, color=C_BLUE, zorder=3, label="proposed trade")
    ax.axhline(0, color=C_GRAY, lw=1, zorder=1)
    ax.set_ylabel("moneyness (strike vs spot, %)")
    ax.set_title("Every proposed trade's moneyness — market hours only")
    _style_axes(ax)
    _draw_day_boundaries(ax, day_segments)
    ax.set_xticks(tick_pos)
    ax.set_xticklabels(tick_lab)
    ax.set_xlim(-0.5, max(tick_pos) + 0.5 if tick_pos else 1)
    fig.tight_layout()
    out = REPORT_DIR / "moneyness.png"
    fig.savefig(out, dpi=150)
    plt.close(fig)
    return out


def chart_equity(days):
    day_groups = [(d, [a for a in day["accounts"] if a.get("account")])
                  for d, day in days.items()]
    id_to_x, day_segments, tick_pos, tick_lab = market_hours_axis(day_groups)

    fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(11, 6.5), sharex=True)
    for day_label, xs, recs in day_segments:
        ax1.plot(xs, [a["account"]["equity"] for a in recs], color=C_BLUE, lw=2)
        ax2.plot(xs, [unreal_total(a) for a in recs], color=C_AMBER, lw=2)
    ax1.set_ylabel("account equity ($)")
    ax1.set_title("Paper-account equity — market hours only\n"
                  "(all P&L UNREALIZED — every position still open, expiry 18 Sep)",
                  fontsize=11.5)
    ax2.axhline(0, color=C_GRAY, lw=1)
    ax2.set_ylabel("unrealized P&L ($)")
    ax2.set_title("Total unrealized mark-to-market P&L across open positions")
    _style_axes(ax1, ax2)
    _draw_day_boundaries(ax1, day_segments)
    _draw_day_boundaries(ax2, day_segments)
    ax2.set_xticks(tick_pos)
    ax2.set_xticklabels(tick_lab)
    ax2.set_xlim(-0.5, max(tick_pos) + 0.5 if tick_pos else 1)
    fig.tight_layout()
    out = REPORT_DIR / "equity_unrealized.png"
    fig.savefig(out, dpi=150)
    plt.close(fig)
    return out


def chart_gate_comparison(days):
    """Trades submitted vs cycles rejected per gate, one bar group per day.
    Seven series: submitted, spread, per-trade notional, aggregate-notional
    (whole-book cap), per-leg position, direction-conflict, degenerate-fit.
    The aggregate-notional and direction-conflict keys were added 2026-09-02;
    older records store 0 for those keys (their fires were counted under the
    parent category in the now-fixed older code)."""
    dates = list(days.keys())
    submitted, spread, notional, agg_notional, position, dir_conflict, degen = (
        [], [], [], [], [], [], []
    )
    for d in dates:
        cycles = days[d]["cycles"]
        gh = lambda k: sum((c.get("gate_hits") or {}).get(k, 0) for c in cycles)
        submitted.append(sum(1 for c in cycles if c.get("dry_run") is False
                             and (c.get("order_result") or {}).get("response") is not None))
        spread.append(gh("spread_gate_hits"))
        notional.append(gh("notional_gate_hits"))
        agg_notional.append(gh("aggregate_notional_hits"))
        position.append(gh("position_gate_hits"))
        dir_conflict.append(gh("direction_conflict_hits"))
        degen.append(sum(1 for c in cycles if (c.get("fit_result") or {}).get("degenerate_fit")))

    C_GREEN = "#15803d"
    C_PINK  = "#be185d"
    series = [
        ("trades submitted",            submitted,    C_BLUE),
        ("spread gate hits",            spread,       C_AMBER),
        ("per-trade notional cap",      notional,     C_TEAL),
        ("aggregate notional cap",      agg_notional, C_GREEN),
        ("position cap (per-leg)",      position,     C_PURPLE),
        ("direction-conflict guard",    dir_conflict, C_PINK),
        ("degenerate-fit rejections",   degen,        C_RED),
    ]
    n = len(series)
    x = list(range(len(dates)))
    width = 0.8 / n

    fig, ax = plt.subplots(figsize=(11, 5.5))
    for i, (label, values, color) in enumerate(series):
        offs = [xi + (i - (n - 1) / 2) * width for xi in x]
        bars = ax.bar(offs, values, width=width * 0.92, color=color, label=label,
                      edgecolor="white", linewidth=0.6)
        ax.bar_label(bars, fontsize=8, color="#374151", padding=2)
    ax.set_xticks(x)
    ax.set_xticklabels(dates)
    ax.set_ylabel("count")
    ax.set_title(
        "Trades submitted vs gate rejections, per day\n"
        "aggregate-notional & direction-conflict keys added 2026-09-02 "
        "(older logs stored those fires in parent categories)"
    )
    ax.legend(loc="upper left", frameon=False, ncols=2, fontsize=8.5)
    _style_axes(ax)
    fig.tight_layout()
    out = REPORT_DIR / "gate_comparison.png"
    fig.savefig(out, dpi=150)
    plt.close(fig)
    return out


def _load_snapshot_index():
    """{embedded snapshot timestamp: parsed snapshot dict}, built once from
    every file in snapshots/. Cycle records only log 'live' as their source
    (not a file path) for scheduler-driven ticks, so this is how a cycle's
    logged fit gets reconnected to the full per-strike quotes it was fit
    against — matched via the timestamp embedded in both places, which is
    generated once per fetch and so is exact, not approximate."""
    index = {}
    for f in SNAP_DIR.glob("*.json"):
        try:
            snap = json.loads(f.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            continue
        if snap.get("timestamp"):
            index[snap["timestamp"]] = snap
    return index


def _clean_cycles_with_snapshot(days, snap_index):
    """
    {day_label: [cycle, ...]} for cycles whose fit succeeded, cleared the
    degenerate-fit guard, AND were matched to their full snapshot (attached
    as cycle['_full_snapshot']). Shared by every chart that needs the raw
    per-strike quotes a cycle was fit against — the 3D smile-evolution mesh
    and the by-day smile overlay both build on this exact same filtering, so
    "clean cycle" means the same thing in both places.
    """
    out = {}
    for d, day in days.items():
        lst = []
        for c in day["cycles"]:
            fit = c.get("fit_result")
            if not fit or fit.get("degenerate_fit") or not fit.get("success", True):
                continue
            snap = snap_index.get((c.get("snapshot") or {}).get("timestamp"))
            if snap is None:
                continue
            c["_full_snapshot"] = snap
            lst.append(c)
        if lst:
            out[d] = lst
    return out


def chart_smile_evolution_3d(days):
    """
    Strike-moneyness x cycle-time x implied-vol mesh across every cycle whose
    fit succeeded and cleared the degenerate-fit guard.

    NOT a volatility surface: Wingman only ever queries a single fixed expiry
    (2026-09-18), so there is no expiry axis in this data — the title and
    z-label say so explicitly and this docstring repeats it so the framing
    survives any refactor.

    DATA CHOICE: uses plot_trisurf on the raw, irregular (moneyness, cycle,
    IV) points rather than interpolating onto a common moneyness grid — the
    live OI filter shifts the liquid strike range cycle to cycle, and
    trisurf's Delaunay triangulation handles that natively without smoothing
    over exactly what was measured. Chosen for honesty about the raw data
    over a smoother but partly-synthetic interpolated surface.
    """
    from wingman.models.fit_utils import call_equivalent_quote, implied_vol_call

    snap_index = _load_snapshot_index()
    n_all_fit = sum(1 for day in days.values() for c in day["cycles"] if c.get("fit_result"))
    day_groups = list(_clean_cycles_with_snapshot(days, snap_index).items())
    id_to_x, day_segments, tick_pos, tick_lab = market_hours_axis(day_groups)
    n_used = sum(len(recs) for _, _, recs in day_segments)
    n_excluded = n_all_fit - n_used

    # Per-day point clouds (kept separate so the triangulation never bridges
    # across a day boundary — same principle as the 2D charts' per-day lines).
    day_points, all_iv = [], []
    for day_label, xs, cycles in day_segments:
        mny, ys, ivs = [], [], []
        for x, c in zip(xs, cycles):
            snap = c["_full_snapshot"]
            fit = c["fit_result"]
            forward, tte, r = fit["forward"], fit["tte"], fit.get("r", 0.0)
            spot = snap["spot"]
            for row in snap.get("strikes", []):
                q = call_equivalent_quote(row, spot, forward, tte, r)
                if q is None:
                    continue
                iv = implied_vol_call(q["mid"], forward, row["strike"], tte, r)
                if iv is None:
                    continue
                mny.append((row["strike"] / spot - 1.0) * 100)
                ys.append(x)
                ivs.append(iv)
        if len(set(ys)) >= 2:  # trisurf needs >1 distinct y per day to triangulate
            day_points.append((day_label, mny, ys, ivs))
            all_iv.extend(ivs)

    if not day_points:
        print("[chart_smile_evolution_3d] no usable cycles — skipping")
        return None

    norm = Normalize(vmin=min(all_iv), vmax=max(all_iv))
    cmap = plt.get_cmap("viridis")

    fig = plt.figure(figsize=(12.5, 9))
    ax = fig.add_subplot(111, projection="3d")
    for day_label, mny, ys, ivs in day_points:
        ax.plot_trisurf(mny, ys, ivs, cmap=cmap, norm=norm, linewidth=0.15,
                        edgecolor="white", antialiased=True, shade=True, alpha=0.97)
    ax.set_xlabel("moneyness: (strike/spot − 1) x 100, %", labelpad=16)
    ax.set_ylabel("cycle (market hours only)", labelpad=14)
    ax.set_zlabel("implied vol", labelpad=8)
    ax.tick_params(axis="x", pad=2)
    ax.set_yticks(tick_pos)
    ax.set_yticklabels(tick_lab, fontsize=7.5)
    ax.view_init(elev=18, azim=-40)
    ax.set_box_aspect((1.6, 2.2, 1))
    ax.xaxis.pane.set_alpha(0.05)
    ax.yaxis.pane.set_alpha(0.05)
    ax.zaxis.pane.set_alpha(0.05)

    sm = ScalarMappable(cmap=cmap, norm=norm)
    sm.set_array([])
    fig.colorbar(sm, ax=ax, shrink=0.55, pad=0.1, label="implied vol")

    ax.set_title(
        "Smile evolution across the trading week\n"
        "NOT a volatility surface — single fixed expiry (2026-09-18), no expiry axis\n"
        f"({n_excluded} degenerate-fit cycles of {n_all_fit} excluded — see reports/README.md)",
        fontsize=11.5,
    )
    out = REPORT_DIR / "smile_evolution_3d.png"
    fig.savefig(out, dpi=150, bbox_inches="tight", pad_inches=0.4)  # 3D axes fight plain tight_layout
    plt.close(fig)
    return out


def chart_smile_by_day(days):
    """
    One representative clean smile per day — market IV vs moneyness — as flat
    2D overlaid lines. Built specifically to check the earlier claim (made
    from reading the 3D chart) that the smile got visibly steeper/noisier
    through the week: a 3D perspective can visually exaggerate or hide a
    trend that a flat overlay either confirms or kills outright.

    REPRESENTATIVE-CYCLE CHOICE: the day's LOWEST price-space fit RMSE (same
    metric as fit_quality.png), not a time-median pick. Reasoning: RMSE
    directly measures how well the fit matches its own day's market quotes,
    so the lowest-RMSE cycle is that day's best-calibrated read of the true
    smile shape — a time-median cycle could easily land on the day's worst
    fit and manufacture "noise" that's really just calibration error.

    Also prints, per day, real (not narrative) numbers: ATM IV from that
    representative curve, and the average sigma2 and average fit RMSE across
    ALL that day's clean cycles (not just the representative one) — this is
    the quantitative check.
    """
    from wingman.models.fit_utils import call_equivalent_quote, implied_vol_call

    snap_index = _load_snapshot_index()
    clean_by_day = _clean_cycles_with_snapshot(days, snap_index)

    palette = [C_BLUE, C_AMBER, C_TEAL, C_PURPLE, C_RED]
    fig, ax = plt.subplots(figsize=(9.5, 6))

    print("\n== SMILE-BY-DAY: quantitative check (clean cycles only) ==")
    header = f"{'date':>12} {'n_clean':>8} {'ATM IV (rep.)':>14} {'avg sigma2':>11} {'avg RMSE':>9}"
    print(header)
    rows_printed = []

    for i, (day_label, cycles) in enumerate(clean_by_day.items()):
        rmses_all = [(c, fit_rmse(c)) for c in cycles]
        rmses_all = [(c, r) for c, r in rmses_all if r is not None]
        if not rmses_all:
            continue
        rep, rep_rmse = min(rmses_all, key=lambda cr: cr[1])

        snap = rep["_full_snapshot"]
        fit = rep["fit_result"]
        forward, tte, r = fit["forward"], fit["tte"], fit.get("r", 0.0)
        spot = snap["spot"]
        mny, ivs = [], []
        for row in snap.get("strikes", []):
            q = call_equivalent_quote(row, spot, forward, tte, r)
            if q is None:
                continue
            iv = implied_vol_call(q["mid"], forward, row["strike"], tte, r)
            if iv is None:
                continue
            mny.append((row["strike"] / spot - 1.0) * 100)
            ivs.append(iv)
        if not mny:
            continue
        order = sorted(range(len(mny)), key=lambda k: mny[k])
        mny_s, ivs_s = [mny[k] for k in order], [ivs[k] for k in order]

        color = palette[i % len(palette)]
        ax.plot(mny_s, ivs_s, color=color, lw=2.4, marker="o", ms=3.5,
                label=f"{day_label}  ({rep['timestamp'][11:16]} UTC, RMSE {rep_rmse:.3f})")

        atm_idx = min(range(len(mny_s)), key=lambda k: abs(mny_s[k]))
        atm_iv = ivs_s[atm_idx]
        avg_sigma2 = sum(c["fit_result"]["sigma2"] for c, _ in rmses_all) / len(rmses_all)
        avg_rmse = sum(r for _, r in rmses_all) / len(rmses_all)
        row = f"{day_label:>12} {len(rmses_all):>8} {atm_iv:>14.4f} {avg_sigma2:>11.4f} {avg_rmse:>9.4f}"
        print(row)
        rows_printed.append((day_label, len(rmses_all), atm_iv, avg_sigma2, avg_rmse))

    ax.axvline(0, color=C_GRAY, lw=1, alpha=0.6, zorder=0)
    ax.set_xlabel("moneyness: (strike/spot − 1) x 100, %")
    ax.set_ylabel("implied vol")
    ax.set_title("One representative smile per day (day's lowest-RMSE clean cycle)\n"
                 "— checking whether the smile actually got steeper/noisier through the week")
    ax.legend(loc="upper right", frameon=False, fontsize=9)
    _style_axes(ax)
    fig.tight_layout()
    out = REPORT_DIR / "smile_by_day.png"
    fig.savefig(out, dpi=150)
    plt.close(fig)
    return out, rows_printed


def gate_effectiveness(days):
    print("\n== 5. GATE EFFECTIVENESS " + "=" * 53)
    all_cycles = [c for day in days.values() for c in day["cycles"]]
    gh = lambda k: sum((c.get("gate_hits") or {}).get(k, 0) for c in all_cycles)
    degen = [c["fit_result"]["degenerate_fit"] for c in all_cycles
             if (c.get("fit_result") or {}).get("degenerate_fit")]
    regime = [c["regime_gate"] for c in all_cycles if isinstance(c.get("regime_gate"), dict)
              and c["regime_gate"].get("decision") in ("full", "half", "stand_down")]
    restrictive = [r for r in regime if r["decision"] in ("half", "stand_down")]
    sample_rat = (restrictive or regime)
    rows = [
        ("spread", gh("spread_gate_hits"),
         "Rejected candidates whose actual execution legs were too wide to keep the "
         "modeled edge. (Reject reason strings are printed, not persisted — counts only.)"),
        ("notional", gh("notional_gate_hits"),
         "No logged rejections since counting began 09-01 (cap raised to $2,500 the "
         "same morning, so ATM straddles fit under it)."),
        ("position", gh("position_gate_hits"),
         "No logged rejections — BUT the cap was still exceeded via fill lag: "
         "C774 reached qty 3 (cap 2) because pending limit orders don't appear in "
         "positions until they fill. Known gap, documented 09-01."),
        ("degenerate-fit", len(degen),
         f"Blocked trading on implausible fits. Real example: \"{degen[0]}\"" if degen
         else "Never fired."),
        ("regime (LLM)", len(restrictive),
         (f"{len(regime)} verdicts issued, {len(restrictive)} restrictive. Example rationale: "
          f"\"{sample_rat[0]['rationale']}\"") if regime else "No verdicts issued."),
    ]
    for name, n, desc in rows:
        print(f"  {name:15} fired {n:3}x  {desc}")
    print("  NOTE: spread/notional/position counts start 2026-09-01 (see section 1 note).")


def summary(days):
    print("\n== 6. WEEK SUMMARY " + "=" * 59)
    all_cycles = [c for day in days.values() for c in day["cycles"]]
    all_accts = [a for day in days.values() for a in day["accounts"] if a.get("account")]
    submitted = [c for c in all_cycles if c.get("dry_run") is False
                 and (c.get("order_result") or {}).get("response") is not None]
    errors = [e for c in all_cycles for e in (c.get("errors") or [])]
    trading_days = sum(1 for day in days.values() if day["accounts"])
    start_eq, end_eq = all_accts[0]["account"]["equity"], all_accts[-1]["account"]["equity"]
    pct = (end_eq / start_eq - 1) * 100
    print(f"  Week so far: {trading_days} trading day(s), {len(all_cycles)} cycles, "
          f"{len(submitted)} orders submitted.")
    print(f"  Equity {start_eq:,.2f} -> {end_eq:,.2f} ({pct:+.2f}%) — ALL of it UNREALIZED "
          "mark-to-market: no position has been closed and every contract expires 18 Sep, "
          "after the hackathon.")
    print(f"  Two model limitations identified and documented (upside-wing moneyness "
          f"artifact; lam->1 mixture degeneracy), {len(errors)} error record(s) logged, "
          "zero unhandled crashes.")
    if errors:
        print(f"  Error records (all handled): {errors[:2]}{' ...' if len(errors) > 2 else ''}")


REPORTS_README = """\
# Wingman reports/

Generated by `python -m wingman.logging.report`, rerun anytime — every file
here is overwritten, nothing is hand-edited. Source: `logs/*.jsonl`.

FRAMING: every P&L figure across these charts is UNREALIZED mark-to-market.
No position has been closed; every contract expires 2026-09-18, after the
hackathon. All 2D x-axes show market hours only (13:30-20:00 UTC), with lines
broken (not connected) at day boundaries — no dead space for closed hours.
The 3D chart uses the same market-hours cycle axis, applied per day.

| File | What it shows |
|---|---|
| `fit_quality.png` | sigma1/sigma2/RMSE per cycle, degenerate-fit rejections marked (x). Monday's isolated bad fits vs Tuesday's sustained degeneracy run, in one image. |
| `moneyness.png` | Moneyness of every proposed trade over time. The upside-wing model artifact shows as a horizontal band around +1.4-2%, not scattered noise. |
| `equity_unrealized.png` | Account equity and total unrealized P&L, continuous across the whole week. |
| `gate_comparison.png` | Trades submitted vs cycles rejected per gate type, one bar group per day — the incident (Monday, unbounded duplication) vs the fix (Tuesday, capped exposure). |
| `smile_evolution_3d.png` | Strike-moneyness x cycle-time x implied-vol mesh, market-hours-only cycle axis, degenerate-fit cycles excluded. **This is NOT a volatility surface** — Wingman only ever queries one fixed expiry (2026-09-18), so there is no expiry axis in this data; it shows how the single-expiry smile's shape moved across the week, nothing more. |
| `smile_by_day.png` | One representative smile per day (that day's lowest-RMSE clean cycle) as flat 2D overlaid lines — built to directly test, not just visually assert, whether the smile got steeper/noisier through the week. Console output from the same run prints the per-day ATM IV, average sigma2, and average fit RMSE behind the chart. |
"""


def main():
    REPORT_DIR.mkdir(exist_ok=True)
    days = load_days()
    if not days:
        print("no logs/*.jsonl files found")
        return
    for d, day in days.items():
        for where, why in day["flagged"]:
            print(f"  FLAG {d} @ {where}: {why}")
    daily_summary(days)
    print("\n== 2. FIT QUALITY CHART ==\n  saved:", chart_fit_quality(days))
    print("\n== 3. MONEYNESS CHART ==\n  saved:", chart_moneyness(days))
    print("\n== 4. EQUITY / UNREALIZED P&L CHART ==\n  saved:", chart_equity(days))
    print("\n== 4b. GATE COMPARISON CHART ==\n  saved:", chart_gate_comparison(days))
    print("\n== 4c. SMILE EVOLUTION (3D) ==\n  saved:", chart_smile_evolution_3d(days))
    smile_by_day_out, _ = chart_smile_by_day(days)
    print("\n== 4d. SMILE BY DAY (2D overlay) ==\n  saved:", smile_by_day_out)
    gate_effectiveness(days)
    summary(days)
    (REPORT_DIR / "README.md").write_text(REPORTS_README, encoding="utf-8")
    print(f"\n  wrote {REPORT_DIR / 'README.md'}")


if __name__ == "__main__":
    main()
